# Generated by Django 5.0.6 on 2024-06-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitsSummaryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('visit_date', models.DateField()),
                ('count', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
    ]
